name: Create onboarding issues

on:
  # This workflow is manually triggered by pressing a button in the UI
  workflow_dispatch:
    # Add GitHub handle of the new team member to assign issues automatically.
    inputs:
      name:
        # Input title
        description: "New team member's GitHub handle"
        # Input has to be provided for the workflow to run
        required: true
        
permissions:
  contents: read
  issues: write 

# Each job bellow will create a new issue from a template
jobs:
   
  issue1:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: JasonEtco/create-an-issue@v2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            assignees: ${{ github.event.inputs.name }}
            filename: .github/explore1.md
            
  issue2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ${{ github.event.inputs.name }}
          filename: .github/learning1
            
  issue3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ${{ github.event.inputs.name }}
          filename: .github/meet4.md
            
  issue4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ${{ github.event.inputs.name }}
          filename: .github/task1.md
          
  issue5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          assignees: ${{ github.event.inputs.name }}
          filename: .github/task2.md
